spring:
  application:
    name: gateway-service
      
server:
  port: 8090

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/